### PR TITLE
Added accessor methods for multibeam1d values

### PR DESCRIPTION
**Pull request by nilsbore**
I needed this for making an interface to the `sensor_msgs::LaserScan` message in ROS. Another PR coming to stonefish_ros for that

### CODE REVIEW

**Comment by patrykcieslak** [comment]
I look into the commits. 
There is one thing I don't like. I can understand getting the vector of angles although it is constant and you can compute it yourself knowing the ranges, just for convenience. However, I don't like getting distances directly, the way you propose. To get the distances you should take the last sample from the sensor, like with all other sensors. The reason is that when you add a sample the parent class automatically adds Gaussian noise if you enable it and ensures that the results are within the limits of sensor range. Getting distances directly you break this idea and it doesn't follow the rest of the sensors.

**Comment by nilsbore** [comment]
Oh, ok, that's indeed a nice thing that we want to have. So I should use something like https://github.com/patrykcieslak/stonefish/blob/master/Library/include/sensors/ScalarSensor.h#L135 together with https://github.com/patrykcieslak/stonefish/blob/master/Library/include/sensors/ScalarSensor.h#L156
to get the number of channels together with the distance values?

**Comment by nilsbore** [comment]
Ok, I think I understand, I'll use the [`getLastSample` method](https://github.com/patrykcieslak/stonefish/blob/master/Library/include/sensors/ScalarSensor.h#L138) and then I use the [`getData` method](https://github.com/patrykcieslak/stonefish/blob/master/Library/include/sensors/Sample.h#L64) of `Sample` to get the actual values.

**Comment by nilsbore** [comment]
Ok, I tried to do it using the samples instead. It turned out that I only needed the `angRange` parameter in that case. Also made accompanying changes inhttps://github.com/patrykcieslak/stonefish_ros/pull/9/files .

**Comment by nilsbore** [comment]
@patrykcieslak Do you want me to squash the commits?

**Pull request merged**
